//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestCard.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountType
    {
        public AccountType()
        {
            this.People = new HashSet<Person>();
            this.PersonChangeRequests = new HashSet<PersonChangeRequest>();
            this.PersonHistories = new HashSet<PersonHistory>();
        }
    
        public int AccountTypeID { get; set; }
        public string AccountTypeName { get; set; }
    
        public virtual ICollection<Person> People { get; set; }
        public virtual ICollection<PersonChangeRequest> PersonChangeRequests { get; set; }
        public virtual ICollection<PersonHistory> PersonHistories { get; set; }
    }
}
