//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestCard.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChangeRequestReason
    {
        public ChangeRequestReason()
        {
            this.TestingCardChangeRequests = new HashSet<TestingCardChangeRequest>();
        }
    
        public int ChangeRequestReasonID { get; set; }
        public string Title { get; set; }
    
        public virtual ICollection<TestingCardChangeRequest> TestingCardChangeRequests { get; set; }
    }
}
