//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestCard.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Code
    {
        public int CodeID { get; set; }
        public int CodeTypeID { get; set; }
        public string Prefix { get; set; }
        public string Suffix { get; set; }
        public int Seed { get; set; }
        public int Length { get; set; }
        public int IncrementStep { get; set; }
        public int Count { get; set; }
    }
}
