//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestCard.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.CompanyChangeRequests = new HashSet<CompanyChangeRequest>();
            this.CompanyHistories = new HashSet<CompanyHistory>();
            this.PersonHistories = new HashSet<PersonHistory>();
            this.People = new HashSet<Person>();
            this.PersonChangeRequests = new HashSet<PersonChangeRequest>();
        }
    
        public int CompanyID { get; set; }
        public string CompanyName { get; set; }
        public Nullable<int> ContactPersonID { get; set; }
        public string Phone { get; set; }
        public string AccreditationScope { get; set; }
        public string AccreditationNumber { get; set; }
        public Nullable<System.DateTime> AccreditationExpireDate { get; set; }
        public Nullable<int> ResponsiblePersonID { get; set; }
        public System.DateTime EffectiveDate { get; set; }
        public string IDNo { get; set; }
        public Nullable<int> FileID { get; set; }
        public string Address { get; set; }
    
        public virtual ICollection<CompanyChangeRequest> CompanyChangeRequests { get; set; }
        public virtual ICollection<CompanyHistory> CompanyHistories { get; set; }
        public virtual ICollection<PersonHistory> PersonHistories { get; set; }
        public virtual File File { get; set; }
        public virtual Person Person { get; set; }
        public virtual Person Person1 { get; set; }
        public virtual ICollection<Person> People { get; set; }
        public virtual ICollection<PersonChangeRequest> PersonChangeRequests { get; set; }
    }
}
