//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestCard.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjectPermission
    {
        public int AccountTypeID { get; set; }
        public int ObjectID { get; set; }
        public int Permission { get; set; }
    
        public virtual AccountType AccountType { get; set; }
        public virtual Object Object { get; set; }
    }
}
