//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestCard.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonDay
    {
        public int PersonID { get; set; }
        public System.DateTime AttendanceDate { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public Nullable<System.TimeSpan> BreakStartTime { get; set; }
        public Nullable<System.TimeSpan> BreakEndTime { get; set; }
        public Nullable<bool> IsLeave { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
