//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestCard.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonScheduleChangeRequest
    {
        public PersonScheduleChangeRequest()
        {
            this.PersonScheduleChangeRequestDetails = new HashSet<PersonScheduleChangeRequestDetail>();
        }
    
        public int PersonScheduleChangeRequestID { get; set; }
        public Nullable<int> PersonID { get; set; }
        public Nullable<int> ResponsiblePersonID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> QualityManagerConfirmStatusID { get; set; }
        public Nullable<System.DateTime> QualityManagerConfirmDate { get; set; }
        public Nullable<int> QualityManagerPersonID { get; set; }
        public Nullable<int> AdministratorConfirmStatusID { get; set; }
        public Nullable<System.DateTime> AdministratorConfirmDate { get; set; }
        public Nullable<int> AdministratorPersonID { get; set; }
    
        public virtual ConfirmStatus AdminConfirmStatus { get; set; }
        public virtual ConfirmStatus QualityManagerConfirmStatus { get; set; }
        public virtual Person Person { get; set; }
        public virtual Person ResponsiblePerson { get; set; }
        public virtual Person AdminPerson { get; set; }
        public virtual Person QualityManagerPerson { get; set; }
        public virtual ICollection<PersonScheduleChangeRequestDetail> PersonScheduleChangeRequestDetails { get; set; }
    }
}
