//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestCard.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonStatistic
    {
        public int PersonID { get; set; }
        public Nullable<int> ScheduleChangeRequestCnt { get; set; }
        public Nullable<int> FilledCardCnt { get; set; }
        public Nullable<int> TestingCardChangeRequestCnt { get; set; }
        public Nullable<decimal> TestingCardDailyAvg { get; set; }
        public Nullable<int> UserOnlineTime { get; set; }
        public Nullable<int> ValidCardCnt { get; set; }
        public Nullable<int> InvalidCardCnt { get; set; }
        public Nullable<int> FirstTestingCnt { get; set; }
        public Nullable<int> SecondaryTestingCnt { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
