//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestCard.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonHistory
    {
        public int PersonHierarchyID { get; set; }
        public int PersonID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string IDNo { get; set; }
        public string SystemIDNo { get; set; }
        public int CompanyID { get; set; }
        public int AccountTypeID { get; set; }
        public Nullable<int> FileID { get; set; }
        public string Password { get; set; }
        public int ResponsiblePersonID { get; set; }
        public System.DateTime EffectiveDate { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual AccountType AccountType { get; set; }
        public virtual Company Company { get; set; }
        public virtual Person Person { get; set; }
        public virtual Person Person1 { get; set; }
        public virtual File File { get; set; }
    }
}
