//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestCard.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonChangeRequest
    {
        public PersonChangeRequest()
        {
            this.PersonScheduleChangeRequests = new HashSet<PersonScheduleChangeRequest>();
        }
    
        public int PersonChangeRequestID { get; set; }
        public Nullable<int> PersonID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string IDNo { get; set; }
        public string SystemIDNo { get; set; }
        public int CompanyID { get; set; }
        public int AccountTypeID { get; set; }
        public Nullable<int> FileID { get; set; }
        public string Password { get; set; }
        public Nullable<int> ResponsiblePersonID { get; set; }
        public System.DateTime EffectiveDate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> QualityManagerConfirmStatusID { get; set; }
        public Nullable<int> AdministratorConfirmStatusID { get; set; }
        public Nullable<int> QualityManagerPersonID { get; set; }
        public Nullable<System.DateTime> QualityManagerConfirmDate { get; set; }
        public Nullable<System.DateTime> AdministratorConfirmDate { get; set; }
        public Nullable<int> AdministratorPersonID { get; set; }
    
        public virtual AccountType AccountType { get; set; }
        public virtual Company Company { get; set; }
        public virtual ConfirmStatus AdminConfirmStatus { get; set; }
        public virtual ConfirmStatus QualityManagerConfirmStatus { get; set; }
        public virtual File File { get; set; }
        public virtual Person AdminPerson { get; set; }
        public virtual Person Person { get; set; }
        public virtual Person QualityManagerPerson { get; set; }
        public virtual Person ResponsiblePerson { get; set; }
        public virtual ICollection<PersonScheduleChangeRequest> PersonScheduleChangeRequests { get; set; }
    }
}
