//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestCard.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonScheduleChangeRequest
    {
        public int PersonScheduleChangeRequestID { get; set; }
        public Nullable<int> PersonID { get; set; }
        public int WeekDayNumber { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public Nullable<System.TimeSpan> BreakStartTime { get; set; }
        public Nullable<System.TimeSpan> BreakEndTime { get; set; }
        public Nullable<int> ResponsiblePersonID { get; set; }
        public System.DateTime EffectiveDate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> QualityManagerConfirmStatusID { get; set; }
        public Nullable<System.DateTime> QualityManagerConfirmDate { get; set; }
        public Nullable<int> QualityManagerPersonID { get; set; }
        public Nullable<int> AdministratorConfirmStatusID { get; set; }
        public Nullable<System.DateTime> AdministratorConfirmDate { get; set; }
        public Nullable<int> AdministratorPersonID { get; set; }
    
        public virtual ConfirmStatus ConfirmStatu { get; set; }
        public virtual ConfirmStatus ConfirmStatu1 { get; set; }
        public virtual Person Person { get; set; }
        public virtual Person Person1 { get; set; }
        public virtual Person Person2 { get; set; }
        public virtual Person Person3 { get; set; }
    }
}
