//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestCard.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestingStep
    {
        public TestingStep()
        {
            this.TestingSubSteps = new HashSet<TestingSubStep>();
        }
    
        public int TestingStepID { get; set; }
        public string TestingStepName { get; set; }
        public Nullable<int> OrderNumber { get; set; }
    
        public virtual ICollection<TestingSubStep> TestingSubSteps { get; set; }
    }
}
